version: "3.9"

services:
  db:
    image: postgres:13.21-alpine3.21
    container_name: postgres_db
    restart: always
    environment:
      PGUSER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-h", "db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_web
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_data:/app/static/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nginx:
      image: nginx:alpine
      container_name: nginx_proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - static_data:/static/
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - web

volumes:
  postgres_data:
  static_data:
